### ISSUE TITLE
Clarify what one needs to do to get the PlusDemonstrator credientials or keystone.

### ISSUE THREAD

**Issue by mavavilj** [SovereignCloudStack/Docs#147] opened 2022-10-13 08:49 UTC
Clarify what one needs to do to get the PlusDemonstrator credientials or keystone.

https://github.com/SovereignCloudStack/Docs/blob/main/PlusDemonstrator/GettingStarted.MD

Here it suggests perhaps implicitly that one must create a PlusServer account. But there's no info about this.
Also, I have no idea what to do with the keystone.

**Comment by frosty-geek** [comment] 2022-10-13 11:33
Actually this should be more an "onboarding" Guide how SCS Community Members/Contributors can get a free of charge project running on gx-scs (aka. scs1 with plusserver) Region.

Terms & Conditions are not clarified either → Code of Conduct should cover this.

**Comment by frosty-geek** [comment] 2022-12-22 15:48
duplicate of #155

**Closed by frosty-geek** 2022-12-22 15:48 UTC
